# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: 
      - "main"
      - "tests"
  pull_request:
    branches: 
      - "main"
      - "tests"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present

    # Run Cypress tests
    - name: Run Cypress Tests
      run: npm run test

    # Generate Allure Report
    - name: Install Allure
      run: npm install allure-commandline --save-dev
    - name: Generate Allure Report
      run: npx allure generate allure-results --clean -o allure-report
    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report